### PR TITLE
CI win + xalan

### PR DESCRIPTION
**Pull request by xzfantom**
As mentioned in #456 one of the working ways to build app for windows is using MSYS2. To avoid finding required libs for different build systems for Windows I added some code to CMakeLists.txt to find it automatically.

### CODE REVIEW

**Review by mikfire — COMMENTED** [review]
Could I talk you into reducing the required Qt5 version to 5.9? 

The Qt5 packages for Ubuntu 18.04LTS are all Qt 5.9.5. We need to maintain support for that version until it drops into extended maintenance mode.

**Comment by mattiasmaahl** [comment]
I may be wrong here, but doesn't QT5.9 break the Test-package for the build?

**Comment by xzfantom** [comment]
> 
> 
> I may be wrong here, but doesn't QT5.9 break the Test-package for the build?

I checked this like few months ago and minimal version for project to build was 5.10. We had open issue on this question here: #521 
I'll check one more time just to be sure.

**Comment by mikfire** [comment]
No need. I've just checked. It does break on 5.9. 

I also verified that you can't build on 18.04LTS with the minimum version of 5.12, at least using the default bionic packages.

**Comment by xzfantom** [comment]
`/home/runner/work/brewtarget/brewtarget/build/src/brewtarget_tests_autogen/EWIEGA46WW/../../../../src/Testing.h:70:22: note: suggested alternative: ‘randomStringGenerator’
          int index = QRandomGenerator().generate64() % posChars.length();
                      ^~~~~~~~~~~~~~~~
                      randomStringGenerator`

QRandomGenerator() was introduced in QT 5.10 only

**Comment by xzfantom** [comment]
> 
> 
> No need. I've just checked. It does break on 5.9.
> 
> I also verified that you can't build on 18.04LTS with the minimum version of 5.12, at least using the default bionic packages.

Maybe add condition and change QRandomGenerator on qrand()?

**Comment by mikfire** [comment]
Ok. I can fix this. A few `#if QT_VERSION` tricks like we are already using through the code base.

If you will set the minimum version to 5.9 and break the tests for a bit, I will submit a PR to fix this issue. I may not be generating cryptographically secure random numbers, but I don't think we need them in this case.

**Comment by mikfire** [comment]
@xzfantom I yield to your solution, and will keep my hands off.

**Comment by xzfantom** [comment]
Added matrix build for Linux, so it's QT5.9.5 and QT12 check

**Review by mikfire — APPROVED** [review]

**Pull request merged**
