### PR TITLE
Partial fix for inventory bug

### PR DESCRIPTION
**Pull request by matty0ung**
This stops the crashing reported in https://github.com/Brewtarget/brewtarget/issues/601, but doesn't fix the problem that not everything has an inventory ID.  (This is fixed in Brewken because, when I rewrote the DB layer, I added some logic that automatically creates an inventory ID for anything that doesn't have one.  That fix will get backported soon, I hope, when I backport the new database layer.)

### CODE REVIEW

**Comment by mattiasmaahl** [comment]
Looks good, also compiles on my machine, although I had to install Boost libraries.
So we have to modify the checks/actions to accommodate this new library.
that is a small issue though.

**Review by mattiasmaahl — APPROVED** [review]
Looking good, I'll approve these changes in hope that the rest of the fix will come with the DB-backport at a later date. 😊
The Boost Library has to be added to the Actions but I'll fix that, I think.

**Comment by matty0ung** [comment]
Thanks.  You could comment out the Boost include if it came to it.  It's just for debugging.  But I think there's a good chance we will end up using another bit of Boost for BeerJSON, so it's worth having it in the build.

**Comment by mattiasmaahl** [comment]
That's what I thought. I have a fix on its way. Creating PR as we speak.

**Pull request merged**
