### PR TITLE
Removed Default Amount field from several editors 

### PR DESCRIPTION
**Pull request by jhmcstanton**
Attached are screenshots of the change + local build
fermentable_editor_update
hop_editor_update

misc_editor_update
yeast_editor_update
local_build

### CODE REVIEW

**Comment by mikfire** [comment]
Can you resolve the conflicts? I will merge the request after that

**Comment by beren12** [comment]
shouldn't this be closed since it's merged?

**Comment by mattiasmaahl** [comment]
Hi @beren12!
This PR is still open.
We're waiting for @jhmcstanton to resolve the conflicts so it can be merged into Brewtarget.

**Comment by matty0ung** [comment]
Just to clarify, this is merged into Brewken but not yet into Brewtarget.  I've done the conflict resolution and will have the fix for Brewtarget in an upcoming PR.  (I'm nearly there on refactoring the code around Units & UnitSystems which is one of the big prerequisites for getting BeerJSON support.)

**Pull request closed without merging**
