### PR TITLE
Run the tests as part of the travisCI script

### PR DESCRIPTION
**Pull request by rocketman768**

### CODE REVIEW

**Comment by rocketman768** [comment]
Ugh, I'm still failing. Looks like the "/usr/local/share/brewtarget cannot be read" dialog.

**Comment by rocketman768** [comment]
Running the tests at least, but passing is blocked on #145

**Comment by mikfire** [comment]
Do you want me to do a separate checkin just to clean databaseschemahelper up, or would you prefer to wait until the postgresql branch is complete?

**Comment by rocketman768** [comment]
This is not a very critical PR, so I'll just wait until yours is ready to merge.

**Comment by rocketman768** [comment]
`Brewtarget::initialize()` is still failing.

**Comment by speshak** [comment]
I have a rebase of this against my fix for #210 (PR #229) here: https://github.com/speshak/brewtarget/tree/feature/travis-testing

**Pull request merged**
