### PR TITLE
Fixes #489 fixing dependencies for Debian build

### LINKED ISSUE #489: dpkg -i deb throws up errors - old dependenices listed as required
Hi, I am trying to build on Ubuntu 20.04. No problem with these steps:

```
$ mkdir brewtarget-build
$ cd brewtarget-build
$ cmake /path/to/brewtarget-src
$ make
$ make package
```

When I get to ``` $ sudo dpkg -i brewtarget_2.4.0_x86_64.deb``` it throws up a bunch of errors:

```
pkg: dependency problems prevent configuration of brewtarget_2.4.0:
 brewtarget_2.4.0 depends on libphonon4 (>= 4:4.2.0); however:
  Package libphonon4 is not installed.
 brewtarget_2.4.0 depends on libqt4-dbus (>= 4:4.5.3); however:
  Package libqt4-dbus is not installed.
 brewtarget_2.4.0 depends on libqt4-network (>= 4:4.5.3); however:
  Package libqt4-network is not installed.
 brewtarget_2.4.0 depends on libqt4-svg (>= 4:4.5.3); however:
  Package libqt4-svg is not installed.
 brewtarget_2.4.0 depends on libqtwebkit4 (>= 2.3.4.dfsg-9.1); however:
  Package libqtwebkit4 is not installed.
 brewtarget_2.4.0 depends on libqt4-xml (>= 4:4.5.3); however:
  Package libqt4-xml is not installed.
 brewtarget_2.4.0 depends on libqtcore4 (>= 4:4.6.1); however:
  Package libqtcore4 is not installed.
 brewtarget_2.4.0 depends on libqtgui4 (>= 4:4.5.3); however:
  Package libqtgui4 is not installed.
 brewtarget_2.4.0 depends on phonon (>= 4:4.5.2); however:
  Package phonon is not installed.

```

Full paste at https://pastebin.com/6f5FvtET

The deb builds and installs fine so I guess it's not a big issue but listing the out of date packages is confusing.

### PR DESCRIPTION
**Pull request by mattiasmaahl**
This fix will autogenerate dependencies for Debian build thus removing the manual step fr updating depency-list when QT updates.

also, with this generated package it is better to use "apt install ./<DEB-PACKAGE-FILE>" instead of "dpkg -i" because apt install will automatically install all dependencies with the package.

closes #489

### CODE REVIEW

**Comment by mattiasmaahl** [comment]
also, this fix is tested on Debian 10 with Cinnamon desktop.
If you want I can spin up a few other flavors to test installation also, just name them and I'll see what I can do.

**Comment by mattiasmaahl** [comment]
Also tested on Fedora 32 
Note: you need to install using `sudo yum -i ./brewtarget_2.4.0_x86_64.rpm` to get the dependencies installed.

**Comment by mikfire** [comment]
This will take more study. 

The files required to create the packages are in other projects (brewtarget/debian-packaging and brewtarget/redhat-packaging). As I barely understand how the packaging works, I do not understand what impact these changes will have on those operations.

**Comment by mattiasmaahl** [comment]
that's fine, let's investigate further on the matter. 
You want me to retract the PR until we have done more investigating?

**Comment by mikfire** [comment]
No. Leave it here, as it will remind me to do it. I just need to play around a little to understand things.

**Comment by mattiasmaahl** [comment]
will do, I'll try to understand it as well, just because I'm curious on the inner workings of packaging. :)

**Comment by mikfire** [comment]
Is this required any longer? I think we've resolved this in other pull requests?

**Comment by xzfantom** [comment]
It's kinda fixed, but in not very good way. 
There is patch in ./build-scripts/linux/ that fixes the problem, The only thing - I think we should move fix from patch to CMakeLists.txt and delete patch.

**Comment by mattiasmaahl** [comment]
I agree with @xzfantom, the patch in Action is basicly the same as this PR if I remember correctly.

**Comment by matty0ung** [comment]
I think the code base has moved on so much since this PR was opened that it's no longer relevant.  If I'm wrong then, of course, please re-open.

**Pull request closed without merging**
