### PR TITLE
Fixes bugs with brewday step numbering (and database version update)

### PR DESCRIPTION
**Pull request by f1oki**
Taken from [here](https://bugs.launchpad.net/brewtarget/+bug/1476047):

*Also, when adding or taking out steps the step numbers do not change correctly; for example I'll end up with two "step 4's" and no step 5.*

It took me some time (had no idea there was a trigger), but I found the bug and fixed it.

Furthermore, found (and fixed) another bug when updating the database version number.

### CODE REVIEW

**Comment by rocketman768** [comment]
Awesome, thank you.

**Comment by rocketman768** [comment]
Can you cherry-pick and repush this against brewtarget/master?

**Comment by rocketman768** [comment]
@Brewtarget/developers this is a heads-up that the database schema is about to change.

**Comment by f1oki** [comment]
For sure! I'll try to do it Friday or during the weekend.

**Comment by rocketman768** [comment]
Will merge this immediately on a rebase to the master branch.

**Pull request closed without merging**
