### PR TITLE
Rebalances the water editor

### PR DESCRIPTION
**Pull request by mikfire**
The water editor was always kind of unpleasant to look at, but I couldn't figure a better way. With the addition of the radar map, I could no longer ignore it and I had a better way.

It still isn't perfect, but this somewhat more digestable.

### CODE REVIEW

**Comment by matty0ung** [comment]
Another newbie question: If I want to download your patch and compile/run it locally, how do I do that?

**Comment by xzfantom** [comment]
> 
> 
> Another newbie question: If I want to download your patch and compile/run it locally, how do I do that?

The easiest way that I found - use Github Desktop. When choosing current branch it shows available pull requests and makes all stuff.
Another way is to add mikfire as git remote and switch to mikfire:feature/watereditor

**Comment by mattiasmaahl** [comment]
Sorry for short answer, on the phone.You run " git fetch upstream pull/<pull id>/head:<local branch name>"Then git checkout <local branch name>I.e.git fetch upstream pull/536/head:somebuggit checkout somebugEasiest way I know of.Skickat från min Galaxy
-------- Originalmeddelande --------Från: Artsiom ***@***.***> Datum: 2021-04-11  21:35  (GMT+02:00) Till: Brewtarget/brewtarget ***@***.***> Kopia: Subscribed ***@***.***> Ämne: Re: [Brewtarget/brewtarget] Rebalances the water editor (#556) 

Another newbie question: If I want to download your patch and compile/run it locally, how do I do that?

The easiest way that I found - use Github Desktop. When choosing current branch it shows available pull requests and makes all stuff.
Another way is to add mikfire as git remote and switch to mikfire:feature/watereditor

**Comment by mikfire** [comment]
I use one of two, depending on the complexity of the change.

You can git clone my repo, switch to the right branch, build and run.

If the change is isolated, like this one, you can make your own branch, copy the one file into place, build and run. 

I tend to use the first a lot, because it's just easy, I've got good bandwidth and a lot of disk space.

**Review by matty0ung — COMMENTED** [review]
Looks good.  My only question would be whether you intended to remove the tabstop lines?  (It means when you hit tab, you go straight from the name field to the notes field, skipping over the numerical entry ones.)

**Comment by mikfire** [comment]
No. I didn't intend on mucking the tab order up.

**Review by matty0ung — APPROVED** [review]

**Pull request merged**
