### PR TITLE
Remove donate buttons

### PR DESCRIPTION
**Pull request by dpettersson**
The donate buttons from the menu (2 button) and from the about box has been removed.

### CODE REVIEW

**Comment by rocketman768** [comment]
Let's reference the issue in the [commit message](https://help.github.com/articles/closing-issues-via-commit-messages/). Try it here by doing `git commit --amend` and changing the commit message to something that includes `closes #92` and then update this pull request with `git push --force origin remove_donate_buttons`.

**Comment by rocketman768** [comment]
Previous merges now conflict with this one. Do `git fetch upstream` followed by `git rebase upstream/master` and fix the conflicts that appear.

**Comment by dpettersson** [comment]
Will do. I can probably fix it tonight.
Den 5 okt 2015 6:47 fm skrev "Philip Lee" <notifications@github.com>:

**Comment by dpettersson** [comment]
I have solved the merge conflicts. I dont understand why the size of the
window had changed (i can't remeber that i did anything to it), but it has
been fixed now.

2015-10-05 6:59 GMT+02:00 Daniel Pettersson <pettson81@gmail.com>:

**Comment by rocketman768** [comment]
No problem Daniel...those xml parameters seem to change if you even *think* about opening the file :)

**Pull request merged**
