### PR TITLE
Enhancement -- Adding two new mash types

### PR DESCRIPTION
**Pull request by mikfire**
This is an enhancement I've been working on for a while, but I think I finally got it right. I've added two new mash types: batchSparge and flySparge. The are considered by most of the code as infusion steps (which they basically are), but they do behave a little differently -- batchSparge assumes you've emptied the mash tun  for example, and adding a flySparge step does not allow you to continue.

This should also close the issue #63

### CODE REVIEW

**Comment by rocketman768** [comment]
There are some conflicts to resolve

    $ git fetch upstream
    $ git merge upstream/develop
    ...carefully fix conflicts...
    $ git push origin feature/newmashtypev2

**Comment by mikfire** [comment]
Did that work? For reasons that escape me, I do not grok git conflict resolution.

**Comment by rocketman768** [comment]
The merge commit looks good. Seems that the conflicts were some pretty trivial stuff in database.c/cpp?

**Comment by mikfire** [comment]
Yeah. The postgresql changes moved some bits around, and this change added
a new parameter in the same places in the header. The conflict in the cpp
file was even more trivial.

I thought I had synced my master branch to the development branch, but
apparently hadn't.

Mik

**Pull request merged**
