### PR TITLE
Added temp calibration option to HydrometerTool.cpp

### PR DESCRIPTION
**Pull request by jawsdaws**
My hydrometer is calibrated to 68F.  The hydrometer tool was set to 60F as the calibrated temperature. I added a field to allow the user to edit the calibrated temp.

### CODE REVIEW

**Comment by dpettersson** [comment]
I haven't used the hydrometertool before, but it seems to work.
I think we should merge this unless @rocketman768  has any objections.

**Comment by jawsdaws** [comment]
I probably should have put this in the request.  Sorry.  I've not used git or github very much.  
I tested this patch against http://www.straighttothepint.com/hydrometer-temperature-correction/ and https://www.brewersfriend.com/hydrometer-temp/  They almost always gave the same results.  The few times there was a difference, it was 0.001 gravity.  Most likely from rounding or approximating on one side or the other.

**Comment by rocketman768** [comment]
👍

**Comment by jawsdaws** [comment]
Thanks guys! Cheers!

**Pull request merged**
