### PR TITLE
Rewriting the Log library to better suite the QT framework.

### PR DESCRIPTION
**Pull request by mattiasmaahl**
This PR will add new functionality to the Logging in Brewtarget.
Short description of what's been updated:
 - Log-Class has been rewritten as a Log Namespace to better suit the Qt Framworks QDebug library.
 - Refined logging and file management
 - Build the log rotation functionality
 - Build a test in QtTest for the logging librarys log rotation functionality.
 - Fixing up Copyright on modified files.

After these changes you can use either Brewtarget:logX(....) functions or use the QDebug- functions directly, i.e. QDebug() << "some nifty debug message" << someVariable;

This is part 1 of Issue #504 to help with logging when importing BeerXML files into Brewtarget

### CODE REVIEW

**Comment by matty0ung** [comment]
This looks good - excellent work!  Really nice to have log file rotation and to be able to write `QDebug << "Foo";` etc.  From looking through the code, I had a couple of questions / minor suggestions, albeit that some are not specific to your changes:

 • For the mappings of LogType_DEBUG, LogType_INFO, etc to “DEBUG”, “INFO”, etc, could these be done via a static array?  Eg `char const * Log::logLevelNames {“INFO”, “DEBUG”, etc};`  Then `assert(QString(Log::logLevelNames[LogType_INFO]) == QString(“INFO”));` etc.  Similarly a couple of arrays could handle the mapping between `LogType_XXX` and `QtXXXMsg`.  It would save a bit of the boilerplate switches and if-thens, and would future enhancements easier (including extending log types and, maybe one day, even translating log messages).

 • In getLogFileList(), the comment says “checking that neither is bigger than the specified size restriction”, but I couldn’t immediately see this happening in the code.

 • Perhaps it's for a future enhancement, but could we one day make LOG_FILE_COUNT and LOG_FILE_SIZE configurable?  (Also, as an aside, do numerical constants such these need to be `#defines`?  Could they be `int const`?  See https://stackoverflow.com/questions/1637332/static-const-vs-define.)

 • Could we use `QMutexLocker` to do RAII and avoid having to do manual matching of `lock()/unlock()` calls on the mutex?

**Comment by mattiasmaahl** [comment]
You make many good points! Will look into the above suggestions tomorrow and see what I can produce.
Thank you very much for hour input!

**Comment by mattiasmaahl** [comment]
I absolutly agree that the LOG_FILE_COUNT and SIZE could be user setting, it's not that hard to implememt either, will fix tomorrow.

I have never used the QMutexLocker but will read up on it tomorrow and make the necessary ajustments. Should not be a big change as there is only two places where the log files are being written or deleted.

The comment above is left over from when I refactored the code at one point, it should be rewritten to better describe what is happening. 😊

**Comment by matty0ung** [comment]
If you haven't used RAII for locks before, I think you'll like it.  It's super elegant IMHO, and I notice its absence when I have to do manual unlocking in languages that don't have RAII.

Instead of using `myMutex.lock();` and having to remember `myMutex.unlock();` on every exit path of the code (including exceptions), you just write `QMutexLocker lockContainer{&myMutex};` to acquire the lock and it is automatically released (by the QMutexLocker destructor) when lockContainer goes out of scope. So you can have a function with multiple returns, or that might throw exceptions, and "everything just works" (TM) with regard to mutex being released.  (And, of course, if you want the scope of the lock to be smaller than a function, just put `{` before acquiring the lock and `}` at the point you want to release it.  Your code is still automatically exception-safe with regard to the mutex.)

**Comment by mattiasmaahl** [comment]
That sounds awsome, it's exactly like context managers in python and alike! I really dig those! Will definitely look into that tomorrow!

**Comment by mattiasmaahl** [comment]
I've managed to implement the above suggestions except the static arrays for LogType, time wasn't allowed for that yet today. 
Will start working on it now, maybe I can manage to get something up today, otherwise I'll look into it tomorrow.
I'm sneaking in some development between work, some days there is much time to code other a little less.

@matty0ung If you could comment on the above commits to start with while I begin to code for the arrays.

**Comment by mattiasmaahl** [comment]
@matty0ung Question, in the Brewtarget class there are these logging functions:
```
void Brewtarget::logW( QString message )
{
   if ( Log::loggingEnabled && Log::logLevel <= Log::LogType_WARNING)
      qWarning() << message;
}
```

As I'm rewriting the Log Library to handle all the checking an mangling of logging types and if there should be any logs written, do we really want these still??

I mean why would we type
`Brewtarget::logD("some message to log");  `
instead of
`qDebug() << "some message to log";`

my thinking here is that the brewtarget log functions do not bring any extra functionality to the program, just one more way to send logs, and being more clunky to use none the less!?

Any thoughts?

**Comment by mattiasmaahl** [comment]
There, Have at it! go nuts! tell me what I screwed up! 😂

joking aside, please review as is now, made quite a few changes and looking forward to your comments and feedback!
Now the Enums are mapped using a char const* array to better translate between enum and string.
also made changes to check the user settings if the logs should be written and if so, to what level.

let me know what you think!

**Comment by matty0ung** [comment]
Cool.  Will have a look.  Re `Brewtarget::logD` vs `qDebug()`, I agree - why re-invent the wheel, especially as (per https://doc.qt.io/qt-5/qtglobal.html#qDebug) qDebug gives you the choice between iostreams-style and printf-style output.  The question is whether you can bear to go through changing all the uses of Brewtarget::logD etc... :smiley:

**Comment by matty0ung** [comment]
On the question about whether logging is enabled, I didn't check what we do at the moment, but I'd be very tempted _not_ to give users the option to turn logging off altogether.  There is an advantage to knowing that the app will always log important things (Errors and Warnings, but also build info) in a known/easily-findable place - eg when a user reports a bug, we often want to ask for the log file to get clues about what's going on.  Of course we could say "please try again with logging turned on" but this assumes the bug (a) is easily reproduceable by the user and (b) does not prevent the app starting up (so the user can easily enable logging through the UI).

**Comment by mattiasmaahl** [comment]
Regarding the logD and friends, of course I can go through and change them all, feel that we shoild have one way of logging and then only have one place to maintain for it. Will have something up tomorrow for that.

Regarding enable/disable logging, when I wrote those settings I thought that the user could have a choice, and as I, at that point, did not have a way to control the file size I opted to have the user disable it by choice. Now that we can control diskusage I can refactor tje options to better suit the new logging library. Will look at it tomorrow!

**Comment by mattiasmaahl** [comment]
I noticed that I had left behind some asserts from my debugging, fixing i a push today.

**Comment by matty0ung** [comment]
Another thought - and apologies for the feedback coming piecemeal - is about filenames.  If I understood the code, we're logging to a file whose name is of the form "Brewtarget_Log_2020_12_18__09_07_23_123.txt" - set in `initLogFileName()` - with all the numbers being a timestamp set either when the app starts up or when we fill up a log file and need to move to the next one.  I see the benefit, that we have easily unique file names and you never need to mess around renaming files.  At the same time, I worry there might be a couple of downsides:
- Every time you stop and start the application, you get a new log file.  So, even if we set max log file size to something big, we might not actually retain that much logging if the max number of log files is small.
- It will be (slightly) harder to get users to submit log files because we have to explain to them what the names mean and how to find the right one.
I wonder if there might be some benefits to having the current log file always called "Brewtarget_Log.txt" and then saving the more complex names for the older files.  That way, log file rotation only happens when the log file is full, and users always know the name of the log file we want them to submit.  WDYT?

**Comment by mattiasmaahl** [comment]
No worries, about the "piecemeal" comments, Commits are cheap! 

Interesting thought, and a was pondering the user of sequential numbering instead. 
for example, always writing to the Brewtarget_log.txt file, but on rotation remove the brewtarget_log_5.log, then rename the others as follows, figured it to be a bit clunky, but I never considered just naming the files with date when rotating and then always writing to the Brewtarget_log.txt, this is an easy fix, will have something up by the end of [my|the] day! 😊

**Comment by mattiasmaahl** [comment]
This push is a Biggie.
replaced all logX( entries in all files with their corresponding QDebug version.

also fixed the logrotation to always write to Brewtarget_Log.txt and renaming them with timestamp when they reach the set size.
all new settings fot this is ready for implementation in the options dialog, but did not have the time today to fix that.

will continue with that in next week, maybe in a new PR? WDYT?

**Comment by matty0ung** [comment]
Good work - thanks @mattiasmaahl.  Yes, I'll approve these changes to get them merged, then further tweaks can be in a separate PR.  (I'm reasonably comfortable that the basic logging functionality will get a fair bit of testing during development.  We'll just want to be sure that we haven't missed any edge cases on rotation etc.)

**Review by matty0ung — APPROVED** [review]

**Comment by jimdbr** [comment]
Is anyone else seeing a build error with this version?

brewtarget/src/Log.cpp:190:47: error: explicit qualification in declaration of ‘QString Log::getTypeName(Log::LogType)’
  190 |    QString Log::getTypeName(const LogType type) {

**Comment by mattiasmaahl** [comment]
> 
> 
> Is anyone else seeing a build error with this version?
> 
> brewtarget/src/Log.cpp:190:47: error: explicit qualification in declaration of ‘QString Log::getTypeName(Log::LogType)’
> 190 | QString Log::getTypeName(const LogType type) {

Good catch jimbr! fixing in a new PR, there is a typo in the declaration that I missed. PR Coming up!

**Comment by mattiasmaahl** [comment]
PR #510 adresses the above bug.

**Comment by matty0ung** [comment]
Some other problems to fix.  I'm getting the following when I run Brewtarget with this new code:
`QDir::mkpath: Empty or null file name
"Log is in a temporary directory: /tmp/Brewtarget_Log.txt"
[08:56:23.600] INFO : "XDG_CONFIG_HOME not set.  HOME directory is /home/matt", in 404`
Can we default to the same log file location as previous versions of the code?

**Comment by mattiasmaahl** [comment]
hmm, that is wierd, did it not find the correct path to make the logging directory in?

I'll have a look at it. To the best of my memory, I did not make that big of a change to the Linux side of directory making, more on the Windows side of things, due to the fact that the program found the wrong directory for APPDATA, but I'll have a look at it and see if I can fix it today.

**Comment by mattiasmaahl** [comment]
@matty0ung I have a new PR for the above issue with the Log file not being able to initialize that early in the process.
Please see #511

**Comment by matty0ung** [comment]
By the way, https://github.com/Brewtarget/brewtarget/pull/506/ is a good example of why we shouldn't ignore compiler warnings.  The warning about brewtarget.cpp:1217 is actually a bug (missing `qWarning() <<` before QString).  Can you include fix in your patch?

**Comment by mattiasmaahl** [comment]
I saw the above, but forgot to include it, will fix tomorrow.

**Pull request merged**
