### PR TITLE
Closes #276. Removed the disconnect

### LINKED ISSUE #276: Disconnected signal/slot pair when printing
A signal/slot pair no longer exits in the QTextBrowser implementation of printing.

```
QObject::disconnect: No such signal QTextBrowser::loadFinished(bool) in /home/philip/myc/brewtarget/rocketman768-brewtarget/src/BrewDayScrollWidget.cpp:135
QObject::disconnect:  (receiver name: 'brewDayScrollWidget')
```

### PR DESCRIPTION
**Pull request by dpettersson**

### CODE REVIEW

**Comment by dpettersson** [comment]
@pricelessbrewing Can you approve this?
I don't think i can approve my own merge request.

**Comment by pricelessbrewing** [comment]
Sorry, meant to. Review approved.

**Comment by dpettersson** [comment]
No problems :)
I have also done that and wondered why it didn't merge :P

**Comment by dpettersson** [comment]
Merging #276

**Comment by dpettersson** [comment]
Man my head is not working today :(

**Pull request merged**
