### PR TITLE
Closes #175: Save/Restore UI state

### LINKED ISSUE #175: Save/Restore UI state
I want to preserve changes to UI layout made by the user. 
I'll save/restore the state of MainWindow splitters, and treeView/tableView headers.

### PR DESCRIPTION
**Pull request by danielm5**

### CODE REVIEW

**Comment by rocketman768** [comment]
Sweet! Are we also saving the overall geometry of the main window? If not, could we (by using [saveGeometry/restoreGeometry](http://doc.qt.io/qt-5/restoring-geometry.html))?

Once that is done, go ahead and squash all these commits together and I'll merge.

**Comment by theophae** [comment]
That's really a good thing ! Thank you Daniel.

**Comment by danielm5** [comment]
MainWindow geometry and state was already being saved.

**Comment by rocketman768** [comment]
:+1:

**Pull request merged**
