### PR TITLE
Build fixes etc for Release 3.0.0 (was 2.4.0)

### PR DESCRIPTION
**Pull request by matty0ung**
I've changed CMakeList.txt, src/CMakeList.txt and QtDesignerPlugins/CMakeLists.txt so that all the build logic and settings are in the first of these 3 files, and the latter 2 just contain lists of source files.

I've turned on more of the CMAKE_AUTOxxx settings and removed all the (now unnecessary) places where we were manually listing .ui files and .h files that need MOC processing etc.

Still in CMakeList.txt, I've tried to put things together that go together and improve commenting.  For Linux, I've also got package building (`make package`) and package lint (`make package_lint`) seemingly working, but it could do with some proper testing.  Will probably need some help getting Windows and Mac packaging working, as I'm currently just pushing commits up to github to see what happens when I change those bits of CMake/CPack, which isn't very productive... :smile: 

On Linux the build process now takes `CHANGES.markdown` and converts it to a Debian-format changelog that can be included in the .deb package.  (The lintian program is quite strict about formats, so there's a bit of not-very-pretty scripting here.  It also doesn't like spelling mistakes, so I've corrected a couple of typos in issue descriptions!)

`CHANGES.markdown` mentions all the closed issues that were modified since the last release in 2016.  Could probably do with going through that and filtering out ones that were closed without code change.

Have also:

- Merged a fix for https://github.com/Brewtarget/brewtarget/issues/645 across from Brewken (because the issue got closed so the fix ought to be in the next release).
- Made a fix for https://github.com/Brewtarget/brewtarget/issues/656 (as it was a relatively straightforward fix for something straight not working).
- Removed `/src/BrewDayWidget.cpp`, `/src/BrewDayWidget.h` and `/ui/BrewDayWidget.ui` as they do not seem to be referenced anywhere and were presumably replaced by BrewDayScrollWidget.xxx a while ago.
- After commenting out `build-scripts/linux/apply-patches.sh` which was breaking the build on Ubuntu 18.04, I then removed the entire `build-scripts` directory (and the sole reference to it) as the contents are no longer used or needed AFAICT.

### CODE REVIEW

**Comment by mattiasmaahl** [comment]
Will try to get windows build tested during the week. Will revert.

**Comment by matty0ung** [comment]
Still fighting with the Windows build.  I've managed to get the build process itself not to barf out obscure errors (by which I mean errors that nobody else seems ever to have reported having!), but I haven't yet worked out how to get `make install` to put all the DLLs in the right place.

**Comment by matty0ung** [comment]
I _think_ this is now working.  If anyone has time to check the Windows and/or Mac packages, that would be great.  If not, we could at least push the Linux release live and then do any further fixes in 3.0.1.

**Comment by matty0ung** [comment]
Eliminated the need to run `make changelog` as a separate step.  Builds are now producing some sort of package on all 3 platforms. Merging everything so we can do the release.

**Pull request merged**
