### PR TITLE
Fixing Log initialization.

### PR DESCRIPTION
**Pull request by mattiasmaahl**
Now it starts to log to file after options has been read.
Early logging is sent to stderr, and Logging is enabled by default.

Error was thrown when Linux did not supply a valid path for log file at initialization, this was changed to only log to stderr at startup.
On windows there was a path supplied on my machine at least, but not on my linux laptop.

### CODE REVIEW

**Comment by matty0ung** [comment]
Can you talk me through how we get to logging to the right place after we've started logging to stderr?  I started reading through the code, but got confused by there being two changeDirectory() functions - one that takes a "defaultDir" parameter (but doesn't seem to get called?) and one that doesn't take any parameters.

**Comment by matty0ung** [comment]
Could we make another couple of tweaks to make this a less surprising upgrade for users?  Default log file name has changed from "brewtarget_log.txt" to "Brewtarget_Log.txt".  Can we change it back?  Also, it was not respecting a previously set log level and switched the setting to INFO.  Did we change the name of the parameter or something?  If so, again, can we change it back?

**Comment by mattiasmaahl** [comment]
Let me look into those issues tomorrow, the name is easy to change, that is just a parameter.
Getting from stderr to file is done by setting the Log::logFilePath and then call Log::changedirectory()

The Log::changedriectory( defaultdir ) function is not in use anymore, that should be removed, I haven't gotten around to it yet.

Let me get back to you on the others tomorrow.😊

**Comment by mattiasmaahl** [comment]
After looking at this some more, I cannot see that the settings was not respected. 

> 
> 
> Could we make another couple of tweaks to make this a less surprising upgrade for users? Default log file name has changed from "brewtarget_log.txt" to "Brewtarget_Log.txt". Can we change it back? Also, it was not respecting a previously set log level and switched the setting to INFO. Did we change the name of the parameter or something? If so, again, can we change it back?

@matty0ung, question on the second part, How do you mean when you say It does not respect the settings? When I was looking in to this I found that the combobox was not displaying the correct level when you go in to change the settings although the setting was saved in the config file.

I fixed this in my code to be pushed, I also changed the name on the log file to lower_case name. added a bunch of comments to try to explain how the logging is initialized, but in short, the logging is initialized to start logging to the stderr/console on startup, then when the app options is read the settings for the logging is updated to start logging to file. this results in that the first logs is always in the console and never lands in the log file, this is not optimal, and I'm trying to figure out a way to get all the logs saved into the final log file somehow, maybe start logging in an temp-file and then copy/move the file to the new location once the location is known? WDYT?

**Comment by mattiasmaahl** [comment]
> 
> 
> Can you talk me through how we get to logging to the right place after we've started logging to stderr? I started reading through the code, but got confused by there being two changeDirectory() functions - one that takes a "defaultDir" parameter (but doesn't seem to get called?) and one that doesn't take any parameters.

in short, the logs are initialized in the Brewtarget::initialize() function, there it starts out logging only to stderr/console. later in the same function when the users/app settings are applied the Log::changedirectory() is called to set the log file and start a textstream to save logs to a file and Console if this is the users preference.
In Brewtarget:initialize() the function readSystemOptions() is called, this will add the settings to the Log namespace but they will not be applied to the logging unless you call the Log::changeDirectory() function. I made it this way because I did not want to have a state in the logging library where somthing was half way set and logging was written.
I'm sure there are better ways to do this, but will require further development down the road. For now I'm trying to fix my f**k-ups! 😂

**Comment by mattiasmaahl** [comment]
Sorry, @mikfire I miss clicked, did not mean to "request a review" from you! 😂😊

**Review by matty0ung — APPROVED** [review]
Looks good - many thanks!

**Comment by matty0ung** [comment]
Sorry for slow replies on my part.  Been a bit busy with a few things going on here that have a hard deadline of 24 Dec! :smiley: 
Thanks for explanation and additional comments.  I agree it makes sense to enable logging to stdout/stderr for the time before we have read in config.
Re the log levels, what happened was that I had set my log level to DEBUG a long time ago and then it went back to being INFO after I merged v1 of the new logging code.  I thought perhaps we'd changed the name of the config parameter or something, but maybe it was just that there was a version of the code that wasn't finding the config file.  Anyway, after I changed it to DEBUG again, it hasn't reverted, so it's OK now.

**Comment by mattiasmaahl** [comment]
No worries on the slow replies! this IS an open source, pro bono if you will, project! there are no requirements to reply in a specific time! 😊

I do value yours and @mikfire replies and comments as they develop and hone my skill in the language, I mostly dabbled in C# and Python, so the whole C++ experience is an old skill not practiced for a long time for me! And I have always been (very) bad at commenting my work, so there is always room for improvement! 
And to be honest, this is the first project I've been involved in that uses the QT framework! 😊 (loving it so far!)

I wish you all a Merry Christmas and a Happy New Year! 🎅

**Pull request merged**
